In [1]:
import pandas as pd 
display(pd.DataFrame({'Yes':[50,21],'No':[53,57]}))
# This is the creation of table using the constructor of DataFrame whose parameters are dictionary and a list
pd.DataFrame({'Students_Name':["Preetham","Sarathi","Jagan"],'Attendance_status':["Present","Absent","Present"]},index=["Student 1","Student 2","Student 3"])

   Yes  No
0   50  53
1   21  57

          Students_Name Attendance_status
Student 1      Preetham           Present
Student 2       Sarathi            Absent
Student 3         Jagan           Present

In [2]:
pd.Series([1,2,3,4,5],index=['Index 0','Index 1','Index 2','Index 3','Index 4'],name='Index of Numbers')

Index 0    1
Index 1    2
Index 2    3
Index 3    4
Index 4    5
Name: Index of Numbers, dtype: int64

In [2]:
import pandas as pd
readv=pd.read_csv("student_performance_dataset.csv",index_col=0)# This index_col tells that which column in the primary key in which all the data depends
display(readv.head(-5)) # This head will give only the first five rows of the dataset
readv.shape # This will give the number of rows and columns present in the dataset

,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
student_id,,,,,,,,,,,
1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
991,Female,2.5,81.4,6.5,NaN,Yes,No,No,81.8,81.9,B
992,Female,5.1,71.7,5.6,Bachelors,Yes,Yes,No,51.0,80.4,B
993,Female,2.6,80.9,7.4,High School,Yes,Yes,No,72.1,78.8,C
994,Female,6.2,87.6,5.9,PhD,Yes,No,No,75.4,92.7,A
995,Female,4.5,75.4,9.4,Bachelors,Yes,Yes,No,69.1,79.1,C

(1000, 11)

In [4]:
readv

,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
student_id,,,,,,,,,,,
1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [5]:
readv.gender

student_id
1         Male
2       Female
3         Male
4         Male
5         Male
         ...
996       Male
997       Male
998     Female
999     Female
1000      Male
Name: gender, Length: 1000, dtype: str

In [6]:
readv['gender'][3]

'Male'

In [7]:
display(readv.iloc[0]) # This will give the row details.These are row first column second indexing functions
readv.iloc[60]

gender                             Male
study_time_hours                    4.0
attendance_percent                 98.0
sleep_hours                         6.5
parental_education            Bachelors
internet_access                     Yes
extracurricular_activities          Yes
part_time_job                        No
previous_grade                     76.9
final_exam_score                  100.0
final_grade                           A
Name: 1, dtype: object

gender                           Male
study_time_hours                  4.0
attendance_percent               79.7
sleep_hours                       7.2
parental_education            Masters
internet_access                   Yes
extracurricular_activities        Yes
part_time_job                      No
previous_grade                   67.4
final_exam_score                 80.4
final_grade                         B
Name: 61, dtype: object

In [8]:
display(readv.iloc[:,0]) #This is the syntax to give the columns of the dataset
display(readv.iloc[:,6])
readv.iloc[:3,0] # This will print the 1st column upto the third row

student_id
1         Male
2       Female
3         Male
4         Male
5         Male
         ...
996       Male
997       Male
998     Female
999     Female
1000      Male
Name: gender, Length: 1000, dtype: str

student_id
1       Yes
2       Yes
3        No
4       Yes
5        No
       ...
996     Yes
997     Yes
998     Yes
999      No
1000     No
Name: extracurricular_activities, Length: 1000, dtype: str

student_id
1      Male
2    Female
3      Male
Name: gender, dtype: str

In [9]:
readv.iloc[1:3,3]# This will print the column data from 1st row till the thrid row so only 2nd row and the third row will be printed
readv.iloc[[0,1,2,3],0]# This will print the 1,2,3,4 rows data of the first column

student_id
1      Male
2    Female
3      Male
4      Male
Name: gender, dtype: str

In [10]:
readv.iloc[-5:]#Negative indexes print the data from the last

,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
student_id,,,,,,,,,,,
996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
import pandas as pd 
rdv=pd.read_csv("student_performance_dataset.csv")
rdv.loc[0,'gender'] # loc is the label based selection operator which gives the data on the row whith the column name

'Male'

In [15]:
# Even multiple rows also can be selected using the label based selection operator loc 
rdv.loc[:,['gender','study_time_hours','attendance_percent']]

     gender  study_time_hours  attendance_percent
0      Male               4.0                98.0
1    Female               6.3               100.0
2      Male               4.9                85.3
3      Male               2.6                77.5
4      Male               2.2                89.6
..      ...               ...                 ...
995    Male               2.8                75.4
996    Male               6.7                88.4
997  Female               2.6                84.5
998  Female               4.6                85.3
999    Male               3.9                77.4

[1000 rows x 3 columns]

In [18]:
# Index Manipulation
rdv.set_index("student_id")# This is used to keep the index that is immuatble same like the primary key so that the data can be related with that entity

,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
student_id,,,,,,,,,,,
1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [20]:
# Conditional selection: This operation prints only the rows if the coniditoin is met,
rdv.loc[rdv.attendance_percent>85]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
6,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6,69.6,D
...,...,...,...,...,...,...,...,...,...,...,...,...
988,989,Female,5.7,96.2,4.8,NaN,Yes,No,No,41.5,80.9,B
989,990,Female,3.2,99.5,5.6,High School,Yes,No,Yes,78.0,93.9,A
993,994,Female,6.2,87.6,5.9,PhD,Yes,No,No,75.4,92.7,A
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B

In [ ]:
# SUMMARY FUCNTIONS AND MAPS
readv.describe()
# Genearates a high level summary

,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,3.570700,85.092300,6.799500,69.740900,83.543500
std,1.478559,9.270685,1.203527,12.613425,10.341333
min,0.500000,54.800000,3.200000,31.300000,46.800000
25%,2.600000,78.800000,5.900000,61.000000,76.075000
50%,3.600000,85.200000,6.800000,69.600000,83.800000
75%,4.500000,91.900000,7.600000,78.400000,91.525000
max,8.100000,100.000000,10.000000,100.000000,100.000000

In [ ]:
readv.attendance_percent.describe()

count    1000.000000
mean       85.092300
std         9.270685
min        54.800000
25%        78.800000
50%        85.200000
75%        91.900000
max       100.000000
Name: attendance_percent, dtype: float64

In [24]:
readv.parental_education.describe()

count             898
unique              4
top       High School
freq              356
Name: parental_education, dtype: object

In [12]:
import pandas as pd
r=pd.read_csv("student_performance_dataset.csv",index_col=0 )
r.head()
r.attendance_percent.mean()
r.describe()
rm=r.study_time_hours.mean()
r.map(lambda p: p -rm)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U4'), dtype('float64')) -> None